import { Metadata } from 'next'
import ClientLayout from '@/app/ClientLayout'
import { Providers } from './providers'
import './globals.css'
import { UserProvider } from './contexts/UserContext'
import { SessionProvider } from 'next-auth/react'
import AuthProviders from './components/Providers'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-gray-900">
        <AuthProviders>
          <Providers>
            <ClientLayout>
              {children}
            </ClientLayout>
          </Providers>
        </AuthProviders>
      </body>
    </html>
  );
}
